import { msg } from '@lingui/core/macro';

export const USER_FEEDBACK_COPY = {
  title: msg`Votre avis compte\n*pour perfectionner RedView*`,
  subtitle: msg`Partagez vos retours terrain pour nous aider à affiner les calques météo, tracés et analyses de performance.`,
  back: msg`← Retour`,
  next: msg`Continuer →`,
  submit: msg`Envoyer mon retour`,
  submitInFlight: msg`Envoi en cours…`,
  successTitle: msg`Merci pour votre précieux retour !`,
  successSubtitle: msg`Vos observations terrain et vos suggestions nous permettent d'améliorer continuellement RedView. Notre équipe examine chaque retour avec attention.`,
  successDone: msg`Fermer`,
  stepProgressLabel: (current: number, total: number) =>
    msg`Étape ${current} sur ${total}`,
  validation: {
    incompleteForm: msg`Veuillez renseigner tous les champs obligatoires avant de continuer.`,
    invalidEmail: msg`Veuillez entrer une adresse e-mail valide.`,
    descriptionTooShort: msg`Veuillez préciser votre retour avec au moins 10 caractères.`,
    submitFailed: msg`Une erreur est survenue lors de l'envoi. Veuillez réessayer dans quelques instants.`,
  },
  fields: {
    firstName: msg`Prénom *`,
    firstNamePlaceholder: msg`Votre prénom`,
    lastName: msg`Nom *`,
    lastNamePlaceholder: msg`Votre nom`,
    email: msg`Adresse e-mail *`,
    emailPlaceholder: msg`vous@exemple.com`,
    emailHint: msg`Votre e-mail sera uniquement utilisé dans le cadre de l'amélioration du service.`,
    country: msg`Pays de pratique *`,
    countryPlaceholder: msg`Sélectionner votre pays`,
    primarySport: msg`Discipline principale *`,
    primarySportPlaceholder: msg`Choisir un sport principal`,
    level: msg`Niveau d'expérience *`,
    levelPlaceholder: msg`Choisir un niveau`,
    annualVolume: msg`Volume annuel estimé *`,
    annualVolumePlaceholder: msg`Choisir ou indiquer une moyenne annuelle`,
    additionalSports: msg`Autres disciplines pratiquées`,
    additionalSportsHint: msg`Sélectionnez les autres activités régulières.`,
    feature: msg`Fonctionnalité concernée *`,
    featurePlaceholder: msg`Choisir une fonctionnalité`,
    feedbackType: msg`Nature du retour *`,
    feedbackTypePlaceholder: msg`Ex : Bug, Vitesse, Suggestion…`,
    description: msg`Description détaillée *`,
    descriptionHint: msg`Décrivez votre observation, le comportement attendu ou votre idée d'amélioration.`,
    descriptionPlaceholder: msg`Décrivez précisément votre retour d'expérience ici…`,
    attachments: msg`Captures d'écran (optionnel)`,
    attachmentsHint: msg`Montrez-nous les écrans ou tracés concernés pour un diagnostic plus rapide.`,
    uploadClickOrDrag: msg`Cliquez ou glissez-déposez vos captures d'écran ici`,
    uploadSubtext: msg`Formats acceptés : PNG, JPG, WebP, SVG, GPX (max. 15 Mo)`,
    removeFile: msg`Supprimer le fichier`,
  },
  stepHeaders: {
    identity: msg`Coordonnées`,
    sports: msg`Pratique sportive`,
    feedback: msg`Votre retour`,
  },
};
