import { msg } from '@lingui/core/macro';

import { TERRAIN_EXPERIENCE_NOTES_MIN_LENGTH } from './data/terrain-experience-notes-min-length';

export const PARTNER_APPLICATION_COPY = {
  title: msg`Rejoignez les partenaires\n*RedView*`,
  subtitle: msg`Vous êtes guide, bureau d'études, formateur ou intégrateur géospatial ? Aidez les praticiens de la montagne à préparer leurs courses et leurs reconnaissances sur un terrain au demi-mètre près.`,
  back: msg`← Retour`,
  next: msg`Suivant →`,
  submit: msg`Envoyer la candidature`,
  submitInFlight: msg`Envoi…`,
  successTitle: msg`Merci pour votre candidature.`,
  successSubtitle: msg`Nous étudions chaque dossier et revenons vers vous s'il y a une correspondance.`,
  successDone: msg`Terminé`,
  stepProgressLabel: (current: number, total: number) =>
    msg`Étape ${current} sur ${total}`,
  validation: {
    incompleteForm: msg`Merci de compléter tous les champs obligatoires avant de continuer.`,
    invalidEmail: msg`Saisissez une adresse e-mail valide.`,
    invalidUrl: msg`Saisissez une URL valide (commençant par http:// ou https://).`,
    invalidAmount: msg`Saisissez un montant valide, en chiffres uniquement.`,
    notesTooShort: msg`Merci de décrire votre projet en au moins ${TERRAIN_EXPERIENCE_NOTES_MIN_LENGTH} caractères.`,
    submitFailed: msg`Nous n'avons pas pu envoyer votre candidature. Réessayez dans un instant.`,
  },
  removeSkill: (skill: string) => msg`Retirer ${skill}`,
  fields: {
    name: msg`Votre nom *`,
    email: msg`E-mail professionnel *`,
    company: msg`Structure ou marque *`,
    website: msg`Site web ou GitHub *`,
    linkedin: msg`Profil LinkedIn`,
    city: msg`Ville *`,
    country: msg`Pays *`,
    countryPlaceholder: msg`Sélectionnez votre pays`,
    countrySearchPlaceholder: msg`Rechercher un pays…`,
    countrySearchEmpty: msg`Aucun pays correspondant.`,
    languages: msg`Langues parlées`,
    typeOfTeam: msg`Type de structure *`,
    typeOfTeamPlaceholder: msg`Indépendant ou bureau ?`,
    partnerScope: msg`Vos domaines d'intervention *`,
    partnerScopeHint: msg`Sélectionnez toutes les catégories qui s'appliquent.`,
    skills: msg`Compétences techniques`,
    skillsHint: msg`Outils, technologies et terrains sur lesquels vous êtes spécialisé. Entrée ou virgule pour ajouter.`,
    skillsPlaceholder: msg`ex. Vol libre, nivologie, topographie, refuge…`,
    terrainExperience: msg`Ce que vous avez réalisé avec RedView *`,
    terrainExperienceHint: msg`Sélectionnez chaque usage que vous avez réellement pratiqué sur un projet — pas ce que vous proposez, ce que vous avez fait.`,
    terrainExperienceNotes: msg`Racontez-nous la mise en œuvre *`,
    terrainExperienceNotesHint: msg`Décrivez un vrai projet RedView (client ou personnel) : pour qui, ce que vous avez préparé, et comment vous avez utilisé les usages sélectionnés. Minimum ${TERRAIN_EXPERIENCE_NOTES_MIN_LENGTH} caractères.`,
    terrainExperienceNotesPlaceholder: msg`Pour qui, ce que vous avez préparé, lesquels des quatre usages vous avez mobilisés…`,
    terrainExperienceProofLink: msg`URL de preuve *`,
    terrainExperienceProofLinkHint: msg`La meilleure preuve d'abord : une instance RedView en ligne, un dépôt public ou un lien YouTube. Loom, Drive et liens de fichiers sont acceptés mais plus lents à examiner.`,
    hourlyRate: msg`Taux horaire *`,
    hourlyRatePlaceholder: msg`150`,
    projectBudgetMin: msg`Budget minimum de projet *`,
    projectBudgetMinPlaceholder: msg`5 000`,
    calendarLink: msg`Lien de réservation / agenda`,
  },
  stepHeaders: {
    identity: msg`Identité`,
    profile: msg`Profil`,
    expertise: msg`Expertise`,
    experience: msg`Expérience`,
    commercials: msg`Conditions`,
  },
};
