import { msg } from '@lingui/core/macro';

import { type CaseStudyCatalogEntry } from './case-study-types';

// The customer stories, in catalog order. The grid features the first and last
// as large cards; the rest are the default two-column cards.
export const CASE_STUDY_CATALOG: readonly CaseStudyCatalogEntry[] = [
  {
    slug: 'navigation-3d-haute-resolution',
    industry: msg`Élévation 3D`,
    title: msg`Navigation 3D haute résolution (40 cm)`,
    summary: msg`Naviguez dans un environnement 3D avec une résolution d'élévation à 40cm, contre 10 à 30m sur les outils standards. Modélisation 3D adaptative (optimisée selon la puissance de votre machine), couverture ultra-précise (France, Corse, Réunion, Suisse) et manipulation fluide en temps réel.`,
    date: msg`Temps réel`,
    readingTime: '40 cm',
    author: 'MNT Haute Définition',
    authorRole: msg`Précision submétrique vs 30m standard`,
    clientIcon: '3d-40cm',
    coverImageSrc: '/images/customers/case-studies/nine-dots.webp',
    kpis: [
      { value: msg`40 cm`, label: msg`Résolution élévation` },
      { value: msg`3D adaptative`, label: msg`Moteur fluide WebGL` },
      { value: msg`FR · CH · DOM`, label: msg`Couverture ultra-précise` },
    ],
    quote: {
      text: msg`Une fidélité topographique sans précédent pour repérer le moindre talus et visualiser le relief avec un réalisme absolu.`,
      author: 'Moteur Géospatial RedView',
      role: msg`Rendu 3D adaptatif temps réel`,
    },
  },
  {
    slug: 'visualisateur-lidar',
    industry: msg`Scan du Sol`,
    title: msg`Visualisateur LiDAR (20 cm)`,
    summary: msg`Obtenez une vue brute du sol avec 20cm de précision pour percer la canopée, identifier les obstacles et vérifier la praticabilité réelle d'un sentier. Rendu WebGPU du nuage de points, analyse des pentes et simulation solaire intégrée.`,
    date: msg`WebGPU HD`,
    readingTime: '20 cm',
    author: 'Scan LiDAR HD',
    authorRole: msg`Moteur WebGPU & Nuage de points`,
    clientIcon: 'lidar-20cm',
    coverImageSrc: '/images/customers/case-studies/alternative-partners.webp',
    kpis: [
      { value: msg`20 cm`, label: msg`Précision brute sol` },
      { value: msg`WebGPU`, label: msg`Moteur nuage de points` },
      { value: msg`Multi-outils`, label: msg`Pentes · Soleil · Tuiles` },
    ],
    quote: {
      text: msg`Le nuage de points LiDAR permet de percer la canopée et d'inspecter chaque passage technique avec une précision brute de 20 cm.`,
      author: 'Moteur WebGPU RedView',
      role: msg`Visualisation LiDAR temps réel`,
    },
  },
  {
    slug: 'analyse-pentes-inclinaisons',
    industry: msg`Topographie & Sécurité`,
    title: msg`Analyse des pentes et inclinaisons`,
    summary: msg`Colorisez les inclinaisons en dégradé ou paliers sur LiDAR MNS 0.40m et MNT 1m. Échelle personnalisable en degrés ou pourcentages avec rendu GPU raster-color-mix pour repérer les seuils d'avalanche (>30°) et replats de bivouac.`,
    date: msg`MNS & MNT`,
    readingTime: 'Degrés / %',
    author: 'Colorimétrie Relief GPU',
    authorRole: msg`MNS 0.40m · MNT 1m · Shaders WebGL`,
    clientIcon: 'slope-analysis',
    coverImageSrc: '/images/customers/case-studies/netzero.webp',
    kpis: [
      { value: msg`0.40m / 1m`, label: msg`Double source MNS/MNT` },
      { value: msg`0° à 90°`, label: msg`Degrés et pourcentages` },
    ],
  },
  {
    slug: 'affichage-paliers-altitude',
    industry: msg`Découpage Relief`,
    title: msg`Affichage par paliers d'altitude`,
    summary: msg`Découpez le relief en tranches d'altitude configurables (2 à 6 couleurs jusqu'à 5 000 m) avec masquage sélectif de bandes pour isoler fonds de vallées, cols et étages alpins.`,
    date: msg`Multi-tranches`,
    readingTime: 'Altitude',
    author: 'Stratification 3D',
    authorRole: msg`Palettes 2-6 couleurs & Masquage`,
    clientIcon: 'altitude-steps',
    coverImageSrc: '/images/customers/case-studies/act-education.webp',
    kpis: [
      { value: msg`2 à 6 couleurs`, label: msg`Palettes étalonnées` },
      { value: msg`Masquage`, label: msg`Isolation des bandes` },
    ],
  },
  {
    slug: 'simulation-ensoleillement-ombres',
    industry: msg`Éclairage & Thermique`,
    title: msg`Simulation de l'ensoleillement et des ombres`,
    summary: msg`Calcul éphéméride SunCalc précis, projection des ombres portées par balayage d'horizon O(N) en Web Worker et carte d'exposition solaire cumulée minute par minute.`,
    date: msg`Éphéméride O(N)`,
    readingTime: 'Temps réel',
    author: 'Moteur Solaire 3D',
    authorRole: msg`SunCalc NOAA & Web Workers O(N)`,
    clientIcon: 'sun-shadows',
    coverImageSrc: '/images/customers/case-studies/w3villa.webp',
    kpis: [
      { value: msg`Balayage O(N)`, label: msg`Ombres Web Worker` },
      { value: msg`Sunlight Map`, label: msg`Ensoleillement cumulé` },
    ],
  },
  {
    slug: 'previsions-meteo-historiques',
    industry: msg`Météo & Climat`,
    title: msg`Prévisions météo et historiques climatiques`,
    summary: msg`Superposez en direct prévisions horaires et tendances climatiques sur le relief 3D : température ressentie, précipitations (mm/h), nébulosité et humidité avec serveur dédié.`,
    date: msg`Live & Archives`,
    readingTime: 'Météo 3D',
    author: 'Agrégateur Météo VPS',
    authorRole: msg`Flux Open-Meteo & Cache temps réel`,
    clientIcon: 'weather-history',
    coverImageSrc: '/images/customers/case-studies/elevate-consulting.webp',
    kpis: [
      { value: msg`5 métriques`, label: msg`Temp, pluie, nuages, vent` },
      { value: msg`Direct & Trends`, label: msg`Prévisions et archives` },
    ],
  },
  {
    slug: 'cartographie-flux-de-vent',
    industry: msg`Aérologie & Effort`,
    title: msg`Cartographie des flux de vent`,
    summary: msg`Moteur de particules WebGL avec mémoire SOA et shaders GLSL à 60 FPS. Échantillonnage de la vitesse, rafales et direction pour anticiper les effets venturi dans les cols.`,
    date: msg`WebGL SOA`,
    readingTime: '60 FPS',
    author: 'Moteur Aérologique GPU',
    authorRole: msg`Particules WebGL & Shaders GLSL`,
    clientIcon: 'wind-flow',
    coverImageSrc: '/images/customers/case-studies/nine-dots.webp',
    kpis: [
      { value: msg`60 FPS`, label: msg`Particules WebGL SOA` },
      { value: msg`Venturi`, label: msg`Vitesse, rafales et cols` },
    ],
  },
  {
    slug: 'modelisation-enneigement',
    industry: msg`Nivologie & Sécurité`,
    title: msg`Modélisation de l'enneigement`,
    summary: msg`Redistribution physique du manteau neigeux couplant AROME 1.1km et LiDAR HD : transport gravitationnel SnowSlide, transport éolien Winstral Sx et régression solaire.`,
    date: msg`AROME HD`,
    readingTime: 'Physique 3D',
    author: 'Modèle Nivologique',
    authorRole: msg`AROME Météo-France & SnowSlide`,
    clientIcon: 'snow-model',
    coverImageSrc: '/images/customers/case-studies/alternative-partners.webp',
    kpis: [
      { value: msg`SnowSlide`, label: msg`Friction gravitationnelle` },
      { value: msg`Winstral Sx`, label: msg`Transport éolien` },
    ],
  },
  {
    slug: 'moteur-itineraire-personnalise',
    industry: msg`Routing Intelligent`,
    title: msg`Moteur d'itinéraire personnalisé`,
    summary: msg`Routage BRouter avec overrides experts : pondération fine des surfaces (single-tracks, gravel, route), contournement des zones protégées et gestion de POIs stratégiques.`,
    date: msg`BRouter Expert`,
    readingTime: 'Multi-profils',
    author: 'Moteur de Routage Expert',
    authorRole: msg`BRouter & Pondération fine surfaces`,
    clientIcon: 'custom-routing',
    coverImageSrc: '/images/customers/case-studies/netzero.webp',
    kpis: [
      { value: msg`Multi-surfaces`, label: msg`Single-track, gravel, route` },
      { value: msg`Zones protégées`, label: msg`Contournement automatique` },
    ],
  },
  {
    slug: 'comparateur-variantes-parcours',
    industry: msg`Analyse Comparative`,
    title: msg`Comparateur de variantes de parcours`,
    summary: msg`Superposition multi-traces simultanée et moteur prédictif Rust WASM (redviewalgo) analysant puissance, courbe de fatigue, CdA, Crr et estimations de temps segment par segment.`,
    date: msg`Rust WASM`,
    readingTime: 'redviewalgo',
    author: 'Moteur Prédictif Rust',
    authorRole: msg`Rust WASM & Algorithme KNN`,
    clientIcon: 'compare-routes',
    coverImageSrc: '/images/customers/case-studies/elevate-consulting.webp',
    kpis: [
      { value: msg`Rust WASM`, label: msg`redviewalgo physique effort` },
      { value: msg`KNN / k-d tree`, label: msg`Prédiction temps FIT/GPX` },
    ],
    quote: {
      text: msg`Superposez vos variantes d'itinéraire et prédisez vos temps de passage grâce à la modélisation physique haute performance en Rust.`,
      author: 'RedView Algo WASM',
      role: msg`Moteur prédictif d'effort et scénarios`,
    },
  },
];
