import { msg } from '@lingui/core/macro';

import { type WebsiteRoute } from './website-route';

export const STATIC_WEBSITE_ROUTES: readonly WebsiteRoute[] = [
  {
    changeFrequency: 'weekly',
    description: msg`RedView : Enlarge your vision. L'environnement 3D géospatial haute résolution (40cm) pour préparer, explorer et sécuriser vos aventures outdoor.`,
    id: 'home',
    indexed: true,
    path: '/',
    priority: 1,
    title: msg`RedView — Enlarge your vision | 3D Geospatial Web`,
  },
  {
    changeFrequency: 'weekly',
    description: msg`Articles, guides méthodologiques et analyses topographiques de terrain par l'équipe RedView.`,
    id: 'blog',
    indexed: true,
    path: '/blog',
    priority: 0.8,
    title: msg`Blog RedView — Guides & Analyses 3D`,
  },
  {
    changeFrequency: 'weekly',
    description: msg`Découvrez et installez les extensions et intégrations RedView en un clic.`,
    id: 'apps',
    indexed: true,
    path: '/apps',
    priority: 0.8,
    title: msg`Applications & Intégrations RedView`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`RedView est 100% accessible gratuitement pendant notre phase de financement participatif. Soutenez les serveurs de calcul 3D et les dalles LiDAR par un don libre ou unique.`,
    id: 'pricing',
    indexed: true,
    path: '/pricing',
    priority: 0.9,
    title: msg`Tarifs & Soutien Participatif — RedView 3D`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`HubSpot gates custom objects behind its $150/seat Enterprise tier. See the full price comparison, with sources, and what RedView includes.`,
    id: 'comparePricingHubspot',
    indexed: true,
    path: '/compare-pricing/hubspot',
    priority: 0.7,
    title: msg`RedView vs HubSpot Pricing — The Real Cost Compared`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Sales Cloud Enterprise lists at $175/user/month before support, sandboxes, and AI add-ons. Compare the real cost with RedView.`,
    id: 'comparePricingSalesforce',
    indexed: true,
    path: '/compare-pricing/salesforce',
    priority: 0.7,
    title: msg`RedView vs Salesforce Pricing — The Real Cost Compared`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`SAP Sales Cloud lists at $134/user/month before a year-one implementation project. Compare with RedView.`,
    id: 'comparePricingSap',
    indexed: true,
    path: '/compare-pricing/sap-sales-cloud',
    priority: 0.7,
    title: msg`RedView vs SAP Sales Cloud Pricing — The Real Cost Compared`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Pipedrive caps automations per company and keeps SSO for its top tier. Compare real per-seat costs with RedView.`,
    id: 'comparePricingPipedrive',
    indexed: true,
    path: '/compare-pricing/pipedrive',
    priority: 0.7,
    title: msg`RedView vs Pipedrive Pricing — The Real Cost Compared`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Dynamics 365 Sales runs $105/user/month plus $40/GB database storage. See the full comparison with RedView.`,
    id: 'comparePricingDynamics',
    indexed: true,
    path: '/compare-pricing/microsoft-dynamics',
    priority: 0.7,
    title: msg`RedView vs Microsoft Dynamics Pricing — The Real Cost Compared`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Trouvez un partenaire certifié RedView pour vous accompagner dans vos déploiements et intégrations géospatiales.`,
    id: 'partners',
    indexed: true,
    path: '/partners',
    priority: 0.7,
    title: msg`Partenaires RedView — Experts Certifiés`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Rejoignez l'écosystème partenaire RedView et développez votre activité.`,
    id: 'partnersApply',
    indexed: false,
    path: '/partners/apply',
    priority: 0.3,
    title: msg`Devenir Partenaire RedView — Candidature`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Rejoignez l'écosystème partenaire RedView : développez, déployez et accompagnez les utilisateurs de la plateforme 3D.`,
    id: 'partnersBecome',
    indexed: true,
    path: '/partners/become',
    priority: 0.6,
    title: msg`Devenir Partenaire RedView — Rejoindre l'Écosystème`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Déposez votre brief projet pour être mis en relation avec un partenaire certifié RedView.`,
    id: 'partnersBrief',
    indexed: false,
    path: '/partners/brief',
    priority: 0.3,
    title: msg`Déposer un Brief Projet — Partenaires RedView`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Une plateforme 3D d'ingénierie outdoor : analyse de la qualité des surfaces, comparaison multi-traces en direct et calcul prédictif des temps de passage.`,
    id: 'whyRedView',
    indexed: true,
    path: '/why-redview',
    priority: 0.8,
    title: msg`Pourquoi RedView — La plateforme d'ingénierie et d'exploration 3D`,
  },
  {
    changeFrequency: 'weekly',
    description: msg`Toutes les mises à jour et nouveautés de RedView : moteurs d'analyse de terrain, cartographie 3D et outils de reconnaissance outdoor.`,
    id: 'releases',
    indexed: true,
    path: '/releases',
    priority: 0.7,
    title: msg`Notes de version RedView — Mises à jour & Nouveautés`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Découvrez toutes les fonctionnalités de RedView : 3D haute résolution 40cm, LiDAR 20cm, analyse des pentes, ensoleillement et routage intelligent.`,
    id: 'customers',
    indexed: true,
    path: '/customers',
    priority: 0.7,
    title: msg`Fonctionnalités RedView — Géospatial 3D & LiDAR Haute Précision`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Explorez le produit RedView : analyse de terrain, comparaison de traces et topographie 3D interactive.`,
    id: 'product',
    indexed: true,
    path: '/product',
    priority: 0.8,
    title: msg`Produit RedView — Plateforme 3D Geospatial & LiDAR`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Mentions légales de la plateforme RedView — Informations sur l'éditeur, l'hébergement et la propriété intellectuelle.`,
    id: 'legalNotice',
    indexed: true,
    path: '/legal-notice',
    priority: 0.3,
    title: msg`Mentions Légales — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Politique de gestion des cookies et traceurs de RedView conforme aux recommandations de la CNIL et du RGPD.`,
    id: 'cookiePolicy',
    indexed: true,
    path: '/cookie-policy',
    priority: 0.3,
    title: msg`Politique de Cookies — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Comment RedView collecte, utilise et protège vos données personnelles — Notre politique conforme au RGPD.`,
    id: 'privacyPolicy',
    indexed: true,
    path: '/privacy-policy',
    priority: 0.3,
    title: msg`Politique de confidentialité — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Les conditions générales régissant l'accès et l'usage de la plateforme géospatiale RedView.`,
    id: 'terms',
    indexed: true,
    path: '/terms',
    priority: 0.3,
    title: msg`Conditions Générales — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Politique de remboursement, droit de rétractation de 14 jours et résiliation sans engagement des souscriptions RedView.`,
    id: 'refundPolicy',
    indexed: true,
    path: '/refund-policy',
    priority: 0.3,
    title: msg`Politique de Remboursement & Rétractation — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Activez votre licence RedView Enterprise et configurez votre instance.`,
    id: 'enterpriseActivate',
    indexed: false,
    path: '/enterprise/activate',
    priority: 0.3,
    title: msg`Enterprise Activation | RedView`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Générateur de trame halftone interactif RedView.`,
    id: 'halftone',
    indexed: false,
    path: '/halftone',
    priority: 0,
    title: msg`Halftone Generator | RedView`,
  },
];
