import { msg } from '@lingui/core/macro';

import { type WebsiteRoute } from './website-route';

export const STATIC_WEBSITE_ROUTES: readonly WebsiteRoute[] = [
  {
    changeFrequency: 'weekly',
    description: msg`Préparez vos aventures outdoor en 3D haute résolution (40 cm) et LiDAR (20 cm). Importez vos traces GPX, analysez pentes, ombres et météo en direct. Gratuit.`,
    id: 'home',
    indexed: true,
    path: '/',
    priority: 1,
    title: msg`RedView — Cartographie 3D Haute Résolution & LiDAR Outdoor`,
  },
  {
    changeFrequency: 'weekly',
    description: msg`Guides méthodologiques, tutoriels d'analyse topographique 3D, exploitation des dalles LiDAR et retours d'expérience outdoor par l'équipe RedView.`,
    id: 'blog',
    indexed: true,
    path: '/blog',
    priority: 0.8,
    title: msg`Blog RedView — Guides Topographiques & Aventures 3D`,
  },
  {
    changeFrequency: 'weekly',
    description: msg`Découvrez et installez les extensions et intégrations RedView en un clic.`,
    id: 'apps',
    indexed: false,
    path: '/apps',
    priority: 0.1,
    robotsDisallow: true,
    title: msg`Applications & Intégrations RedView`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Accédez à 100% de RedView gratuitement en avant-première. Soutenez l'infrastructure de calcul 3D et d'hébergement LiDAR par un don libre ou unique.`,
    id: 'pricing',
    indexed: true,
    path: '/pricing',
    priority: 0.9,
    title: msg`Tarifs & Accès Gratuit — RedView Cartographie 3D`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Trouvez un partenaire certifié RedView pour vous accompagner dans vos déploiements et intégrations géospatiales.`,
    id: 'partners',
    indexed: true,
    path: '/partners',
    priority: 0.7,
    title: msg`Partenaires RedView — Experts Certifiés`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Rejoignez l'écosystème partenaire RedView et développez votre activité.`,
    id: 'partnersApply',
    indexed: false,
    path: '/partners/apply',
    priority: 0.3,
    title: msg`Devenir Partenaire RedView — Candidature`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Rejoignez l'écosystème partenaire RedView : développez, déployez et accompagnez les utilisateurs de la plateforme 3D.`,
    id: 'partnersBecome',
    indexed: true,
    path: '/partners/become',
    priority: 0.6,
    title: msg`Devenir Partenaire RedView — Rejoindre l'Écosystème`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Déposez votre brief projet pour être mis en relation avec un partenaire certifié RedView.`,
    id: 'partnersBrief',
    indexed: false,
    path: '/partners/brief',
    priority: 0.3,
    title: msg`Déposer un Brief Projet — Partenaires RedView`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Pourquoi RedView surpasse les cartes classiques : précision submétrique à 40 cm, LiDAR 20 cm et outils d'ultra-endurance conçus par des pratiquants de terrain.`,
    id: 'whyRedView',
    indexed: true,
    path: '/why-redview',
    priority: 0.8,
    title: msg`Pourquoi Choisir RedView — L'Excellence Cartographique 3D`,
  },
  {
    changeFrequency: 'weekly',
    description: msg`Découvrez les dernières améliorations de RedView : performances du moteur 3D, intégration de nouvelles dalles LiDAR et outils de navigation outdoor.`,
    id: 'releases',
    indexed: true,
    path: '/releases',
    priority: 0.7,
    title: msg`Mises à jour & Nouveautés — Journal de Version RedView`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Toutes les fonctionnalités RedView : LiDAR 20 cm sans végétation, analyse des pentes, ensoleillement physique, flux de vent et prévisions nivologiques 3D.`,
    id: 'customers',
    indexed: true,
    path: '/customers',
    priority: 0.7,
    title: msg`Fonctionnalités RedView — Outils 3D & Analyse de Terrain`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Explorez la technologie RedView : relief submétrique 40 cm, dalles LiDAR 20 cm sans canopée, simulation solaire astronomique et analyse de traces GPX.`,
    id: 'product',
    indexed: true,
    path: '/product',
    priority: 0.8,
    title: msg`Moteur 3D & Technologie Cartographique — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Mentions légales de la plateforme RedView — Informations sur l'éditeur, l'hébergement et la propriété intellectuelle.`,
    id: 'legalNotice',
    indexed: true,
    path: '/legal-notice',
    priority: 0.3,
    title: msg`Mentions Légales — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Politique de gestion des cookies et traceurs de RedView conforme aux recommandations de la CNIL et du RGPD.`,
    id: 'cookiePolicy',
    indexed: true,
    path: '/cookie-policy',
    priority: 0.3,
    title: msg`Politique de Cookies — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Comment RedView collecte, utilise et protège vos données personnelles — Notre politique conforme au RGPD.`,
    id: 'privacyPolicy',
    indexed: true,
    path: '/privacy-policy',
    priority: 0.3,
    title: msg`Politique de confidentialité — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Les conditions générales régissant l'accès et l'usage de la plateforme géospatiale RedView.`,
    id: 'terms',
    indexed: true,
    path: '/terms',
    priority: 0.3,
    title: msg`Conditions Générales — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Politique de remboursement, droit de rétractation de 14 jours et résiliation sans engagement des souscriptions RedView.`,
    id: 'refundPolicy',
    indexed: true,
    path: '/refund-policy',
    priority: 0.3,
    title: msg`Politique de Remboursement & Rétractation — RedView`,
  },
  {
    changeFrequency: 'yearly',
    description: msg`Activez votre licence RedView Enterprise et configurez votre instance.`,
    id: 'enterpriseActivate',
    indexed: false,
    path: '/enterprise/activate',
    priority: 0.3,
    title: msg`Enterprise Activation | RedView`,
  },
  {
    changeFrequency: 'monthly',
    description: msg`Générateur de trame halftone interactif RedView.`,
    id: 'halftone',
    indexed: false,
    path: '/halftone',
    priority: 0,
    title: msg`Halftone Generator | RedView`,
  },
];
